Instagram App/Models/ErrorViewModel.cs
namespace Instagram_App.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Instagram App/Models/home.cs
namespace Instagram_App.Models
{
    public class home
    {
        public int Id { get; set; }
        public string? PostLink { get; set; }

        public string? PostName { get; set; }
        public int PostLikeCount { get; set; }

        public home()
        {
            
        }
    }
}

Instagram App/Controllers/HomeController.cs
using Instagram_App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Instagram_App.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Instagram App/Controllers/homesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Instagram_App.Data;
using Instagram_App.Models;
using Microsoft.AspNetCore.Authorization;

namespace Instagram_App.Controllers
{
    [Authorize]
    public class homesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public homesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: homes
        public async Task<IActionResult> Index()
        {
            return View(await _context.home.ToListAsync());
        }
        // GET: homes/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        // POST: homes/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.home.Where(j => j.PostName.Contains(SearchPhrase)).ToListAsync());
        }
        
        // GET: homes1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var home = await _context.home
                .FirstOrDefaultAsync(m => m.Id == id);
            if (home == null)
            {
                return NotFound();
            }

            return View(home);
        }
        // GET: homes1/Create
        public IActionResult Create()
        {
            return View();
        }
        // POST: homes1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PostLink,PostName,PostLikeCount")] home home)
        {
            if (ModelState.IsValid)
            {
                _context.Add(home);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(home);
        }
        // GET: homes1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var home = await _context.home.FindAsync(id);
            if (home == null)
            {
                return NotFound();
            }
            return View(home);
        }
        // POST: homes1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PostLink,PostName,PostLikeCount")] home home)
        {
            if (id != home.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(home);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!homeExists(home.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(home);
        }
        // GET: homes1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var home = await _context.home
                .FirstOrDefaultAsync(m => m.Id == id);
            if (home == null)
            {
                return NotFound();
            }

            return View(home);
        }
        // POST: homes1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var home = await _context.home.FindAsync(id);
            if (home != null)
            {
                _context.home.Remove(home);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool homeExists(int id)
        {
            return _context.home.Any(e => e.Id == id);
        }
    }
}

Instagram App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Instagram</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Social Media Web apps with ASP.NET Core</a>.</p>
</div>

Instagram App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Instagram_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Instagram_App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-papayawhip border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Instagram_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="homes" asp-action="Index">IGHome</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="homes" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Instagram_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Instagram App/Views/homes/Create.cshtml
@model Instagram_App.Models.home

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>home</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PostLink" class="control-label"></label>
                <input asp-for="PostLink" class="form-control" />
                <span asp-validation-for="PostLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostName" class="control-label"></label>
                <input asp-for="PostName" class="form-control" />
                <span asp-validation-for="PostName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostLikeCount" class="control-label"></label>
                <input asp-for="PostLikeCount" class="form-control" />
                <span asp-validation-for="PostLikeCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Instagram App/Views/homes/Delete.cshtml
@model Instagram_App.Models.home

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>home</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostLikeCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostLikeCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Instagram App/Views/homes/Details.cshtml
@model Instagram_App.Models.home

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>home</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostLink)
        </dt>
        <div class="row">

        <dd class = "col-sm-10">
            <img src=@Html.DisplayFor(model => model.PostLink) alt=@Html.DisplayFor(model => model.PostLink) width="200" 
     height="300" />
        </dd>
            <div />
        @*<dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostLink)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostLikeCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostLikeCount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Instagram App/Views/homes/Edit.cshtml
@model Instagram_App.Models.home

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>home</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PostLink" class="control-label"></label>
                <input asp-for="PostLink" class="form-control" />
                <span asp-validation-for="PostLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostName" class="control-label"></label>
                <input asp-for="PostName" class="form-control" />
                <span asp-validation-for="PostName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostLikeCount" class="control-label"></label>
                <input asp-for="PostLikeCount" class="form-control" />
                <span asp-validation-for="PostLikeCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Instagram App/Views/homes/Index.cshtml
@model IEnumerable<Instagram_App.Models.home>

@{
    ViewData["Title"] = "Index";
}

<h1>Home</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PostLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostLikeCount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    <img src=@Html.DisplayFor(modelItem => item.PostLink) alt=@Html.DisplayFor(modelItem => item.PostLink) width="200" 
     height="300" />
                
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.PostLink)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.PostName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostLikeCount)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Instagram App/Views/homes/ShowSearchForm.cshtml
<h4>Search for IG Post's</h4>
<hr />
<div class="row">
    <div class="col-md-4">
      
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label" ></label>
                <input name="SearchPhrase" class="form-control"/>
            </div>
           <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
       
        
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>